import {useEffect,useState} from 'react';
import {api} from './api.js';
import Register from './components/Register/Register.jsx';

function ErrorMessage({message}) { return message ? <p className="error" role="alert">{message}</p> : null; }
function Login({onLogin}) {
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{const result=await api('login',Object.fromEntries(new FormData(event.currentTarget)));onLogin(result.userName);window.location.assign('/dealers');}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <section className="form-panel"><p className="eyebrow">WELCOME BACK</p><h1>Log in to OpenRoad</h1><p>Share a review and help someone choose their next dealership.</p><form onSubmit={submit}><label>Username<input name="userName" autoComplete="username" maxLength="150" required/></label><label>Password<input type="password" name="password" autoComplete="current-password" maxLength="256" required/></label><ErrorMessage message={error}/><button disabled={busy}>{busy?'Logging in…':'Log in'}</button></form><p>New here? <a href="/register">Create an account</a></p></section>;
}
function Dealers({user}) {
  const [dealers,setDealers]=useState([]);const [state,setState]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;api('get_dealers').then(result=>{if(active)setDealers(result.dealers);}).catch(err=>{if(active)setError(err.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const states=[...new Set(dealers.map(d=>d.state))].sort();const filtered=state?dealers.filter(d=>d.state===state):dealers;
  return <><section className="hero"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h1>A better drive starts<br/>with a trusted dealer.</h1><p>Explore dealerships across the country. Read real experiences. Share your own.</p><a className="button" href="#dealership-list">Find a dealership <span aria-hidden="true">↗</span></a></div><img src="/static/car_dealership.jpg" alt="Cars displayed outside a dealership"/></section>
  <section id="dealership-list"><div className="section-head"><div><p className="eyebrow">THE DEALERSHIP DIRECTORY</p><h2>Find your local branch</h2></div><label className="filter">Filter by state<select value={state} onChange={e=>setState(e.target.value)}><option value="">Show all states</option>{states.map(s=><option key={s}>{s}</option>)}</select></label></div><ErrorMessage message={error}/>{loading?<p role="status">Loading dealerships…</p>:<><p className="muted">{filtered.length} dealership{filtered.length===1?'':'s'}{state?' in '+state:''}</p><div className="table-wrap"><table><thead><tr><th>Dealership</th><th>City</th><th>State</th><th>Address</th>{user&&<th>Share your experience</th>}</tr></thead><tbody>{filtered.map(d=><tr key={d.id}><td><a href={'/dealer/'+d.id}>{d.full_name}</a></td><td>{d.city}</td><td>{d.state}</td><td>{d.address}, {d.zip}</td>{user&&<td><a className="text-button" href={'/postreview/'+d.id}>Review Dealer</a></td>}</tr>)}</tbody></table></div>{!filtered.length&&!error&&<p>No dealerships match this state.</p>}</>}</section></>;
}
function Dealer({id,user}) {
 const [dealer,setDealer]=useState(null); const [reviews,setReviews]=useState([]); const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([api('dealer/'+id),api('reviews/dealer/'+id)]).then(([d,r])=>{if(active){setDealer(d.dealer[0]);setReviews(r.reviews);}}).catch(err=>{if(active)setError(err.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id]);
 return <section><a href="/dealers">← All dealerships</a><ErrorMessage message={error}/>{loading&&<p role="status">Loading dealership…</p>}{dealer&&<><div className="detail-hero"><div><p className="eyebrow">{dealer.state} / {dealer.city}</p><h1>{dealer.full_name}</h1><p>{dealer.address}, {dealer.city}, {dealer.state} {dealer.zip}</p></div><a className="button" href={user?'/postreview/'+id:'/login'}>{user?'Review Dealer':'Log in to write a review'}</a></div><div className="section-head"><h2>Customer experiences</h2><span className="muted">{reviews.length} review{reviews.length===1?'':'s'}</span></div><div className="review-grid">{reviews.map(review=><article className="card review-card" key={review.id}><div className="review-meta"><strong>{review.name}</strong><span className={'sentiment '+review.sentiment}>{review.sentiment || 'neutral'}</span></div><p className="review-text">{review.review}</p>{review.purchase&&<p className="muted">Purchased {review.car_year} {review.car_make} {review.car_model}<br/>{review.purchase_date}</p>}<time className="muted" dateTime={review.time}>{review.time?new Date(review.time).toLocaleDateString():''}</time></article>)}</div>{!reviews.length&&<p>Be the first to share an experience with this dealership.</p>}</>}</section>;
}
function PostReview({id,user}) {
 const [dealer,setDealer]=useState(null);const [cars,setCars]=useState([]);const [purchase,setPurchase]=useState(false);const [make,setMake]=useState('');const [model,setModel]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;Promise.all([api('dealer/'+id),api('get_cars')]).then(([d,c])=>{if(active){setDealer(d.dealer[0]);setCars(c.models);}}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[id]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('add_review',{dealership:Number(id),review:data.review,purchase,car_id:purchase?Number(data.car_id):null,purchase_date:data.purchase_date||''});window.location.assign('/dealer/'+id);}catch(err){setError(err.message);}finally{setBusy(false);}}
 if(!user)return <section className="form-panel"><h1>Log in to write a review</h1><a className="button" href="/login">Log in</a></section>;
 const makes=[...new Set(cars.map(c=>c.make))];const models=[...new Set(cars.filter(c=>c.make===make).map(c=>c.model))];
 return <section className="form-panel wide"><a href={'/dealer/'+id}>← Back to dealership</a><p className="eyebrow">YOUR EXPERIENCE MATTERS</p><h1>Review {dealer?.full_name||'this dealership'}</h1><form onSubmit={submit}><label>Your review<textarea name="review" rows="5" maxLength="3000" required placeholder="What went well? What could be better?"/></label><label className="check"><input type="checkbox" checked={purchase} onChange={e=>setPurchase(e.target.checked)}/>I purchased a vehicle</label>{purchase&&<><div className="form-row"><label>Car make<select value={make} onChange={e=>{setMake(e.target.value);setModel('');}} required><option value="">Choose make</option>{makes.map(m=><option key={m}>{m}</option>)}</select></label><label>Car model<select value={model} onChange={e=>setModel(e.target.value)} required><option value="">Choose model</option>{models.map(m=><option key={m}>{m}</option>)}</select></label></div><div className="form-row"><label>Car year<select name="car_id" required><option value="">Choose year</option>{cars.filter(c=>c.make===make&&c.model===model).map(c=><option value={c.id} key={c.id}>{c.year}</option>)}</select></label><label>Purchase date<input type="date" name="purchase_date" max={new Date().toISOString().slice(0,10)} required/></label></div></>}<ErrorMessage message={error}/><button disabled={busy||!dealer}>{busy?'Submitting…':'Submit review'}</button></form></section>;
}
export default function App(){
 const [user,setUser]=useState(null);const [ready,setReady]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{api('session').then(result=>setUser(result.userName)).catch(err=>setError(err.message)).finally(()=>setReady(true));},[]);
 async function signout(){try{await api('logout',{});setUser(null);window.location.assign('/dealers');}catch(err){setError(err.message);}}
 const route=window.location.pathname;const match=route.match(/^\/(dealer|postreview)\/(\d+)$/);
 return <><header><a href="/" className="brand"><span className="brand-icon" aria-hidden="true">↗</span>OpenRoad</a><nav aria-label="Main navigation"><a href="/dealers">Dealerships</a><a href="/about">About us</a><a href="/contact">Contact</a></nav><div className="account">{user?<><span>Welcome, <strong>{user}</strong></span><button className="quiet" onClick={signout}>Log out</button></>:<><a href="/login">Log in</a><a className="button small" href="/register">Sign up</a></>}</div></header><main><ErrorMessage message={error}/>{!ready?<p role="status">Loading…</p>:route==='/register'?<Register onLogin={setUser}/>:route==='/login'?<Login onLogin={setUser}/>:match?.[1]==='dealer'?<Dealer id={match[2]} user={user}/>:match?.[1]==='postreview'?<PostReview id={match[2]} user={user}/>:<Dealers user={user}/>}</main><footer><a className="brand" href="/">OpenRoad</a><span>A clearer view of your next dealership.</span><p>Educational demonstration • Fictional company and supplied course data</p></footer></>;
}
